networks:
    default:
        name: engage_network
        external: TRUE

services:
    mssql:
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: SuperP4ssword!
        healthcheck:
            test: |
                /opt/mssql-tools/bin/sqlcmd \
                    -S localhost -U sa -P "$$SA_PASSWORD" \
                    -Q "SELECT 1" || exit 1
        image: mcr.microsoft.com/mssql/server:2019-CU12-ubuntu-20.04
        ports:
            - 1433:1433

    mssql-startup:
        build: mssql
        depends_on:
            - mssql
        environment:
            MSSQL_HOST: mssql
            MSSQL_PORT: 1433
            MSSQL_USER: sa
            MSSQL_PASSWD: SuperP4ssword!
            CSV_PATH: /home/mssql/output/csv

    hadoop:
        build: hadoop
        healthcheck:
            test: wget --spider localhost:9870 || exit 1
            timeout: 90s
        volumes:
            - ./config:/etc/hadoop
        ports:
            - 9870:9870
            - 8020:8020

    hadoop-datanode:
        build: hadoop
        command: hdfs datanode
        depends_on:
            - hadoop
        volumes:
            - ./config:/etc/hadoop
        healthcheck:
            test: wget --spider localhost:9864 || exit 1
            timeout: 90s

    mongodb:
        command: --replSet debezium --keyFile /mongo-storage/keyfile
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        healthcheck:
            test: |
                mongo --eval 'db.runCommand("ping").ok' \
                    localhost:27017/test --quiet
        image: mongo:5.0.2
        ports:
            - 27017:27017
        volumes:
            - mongo-storage:/mongo-storage
            - ./mongo/scripts/wait-for-keyfile.sh:/docker-entrypoint-initdb.d/wait-for-keyfile.sh

    mongodb-rs:
        command: --replSet debezium --keyFile /mongo-storage/keyfile
        healthcheck:
            test: |
                mongo --eval 'db.runCommand("ping").ok' \
                    localhost:27017/test --quiet
        image: mongo:5.0.2
        volumes:
            - mongo-storage:/mongo-storage
            - ./mongo/scripts/wait-for-keyfile.sh:/docker-entrypoint-initdb.d/wait-for-keyfile.sh

    mongodb-startup:
        build: mongo
        depends_on:
            - mongodb
            - mongodb-rs
        volumes:
            - mongo-storage:/mongo-storage

    mongodb-ui:
        image: mongo-express
        depends_on:
            - mongodb
            - mongodb-rs
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_AUTH_USERNAME: root
            ME_CONFIG_MONGODB_AUTH_PASSWORD: root
        healthcheck:
            test: wget --spider localhost:8081 || exit 1
        ports:
            - 8081:8081

    redis:
        image: redis:6.2.5-alpine
        healthcheck:
            test: redis-cli ping || exit 1
        ports:
            - 6379:6379

volumes:
    mongo-storage:

version: '3.8'
