networks:
    default:
        name: engage_network
        external: TRUE

services:
    spark-raw-sink:
        build: spark
        command: src/streaming_factory.py raw_streamer
        environment:
            BROKER_HOSTNAME: dbz-kafka:9092
            SPARK_UI_PORT: 4040
        ports:
            - 4040:4040
        volumes:
            - ./spark/src:/opt/spark/src
            - ./config:/etc/hadoop
            - checkpoint:/checkpoint

    spark-trusted-sink:
        build: spark
        command: src/streaming_factory.py trusted_streamer
        environment:
            BROKER_HOSTNAME: dbz-kafka:9092
            SPARK_UI_PORT: 4041
        ports:
            - 4041:4041
        volumes:
            - ./spark/src:/opt/spark/src
            - ./config:/etc/hadoop
            - checkpoint:/checkpoint

    spark-groups-ranking:
        build: spark
        command: src/streaming_factory.py groups_streamer
        environment:
            BROKER_HOSTNAME: dbz-kafka:9092
            SPARK_UI_PORT: 4042
        ports:
            - 4042:4042
        volumes:
            - ./spark/src:/opt/spark/src
            - ./config:/etc/hadoop
            - checkpoint:/checkpoint

volumes:
    checkpoint:
        driver: local

version: '3.8'
