networks:
    default:
        name: engage_network
        external: TRUE

services:
    spark-raw-sink:
        build: spark
        command: src/streaming_factory.py raw_streamer
        environment:
            BROKER_HOSTNAME: dbz-kafka:9092
        volumes:
            - ./spark/src:/opt/spark/src
            - ./config:/etc/hadoop

    spark-trusted-sink:
        build: spark
        command: src/streaming_factory.py trusted_streamer
        environment:
            BROKER_HOSTNAME: dbz-kafka:9092
        volumes:
            - ./spark/src:/opt/spark/src
            - ./config:/etc/hadoop

version: '3.8'
