networks:
    default:
        name: engage_network
        external: TRUE

services:
    spark-raw-streamer:
        build: spark
        command: src/streaming_factory.py raw_streamer
        environment:
            BROKER_HOSTNAME: dbz-kafka:9092
            HADOOP_HOSTNAME: hadoop:8020
            SPARK_NUM_EXECUTOR: 4
            SPARK_EXECUTOR_CORES: 1
            SPARK_EXECUTOR_MEMORY: 16GB
            SPARK_UI_PORT: 4040
        ports:
            - 4040:4040
        volumes:
            - checkpoint:/checkpoint

    spark-context-streamer:
        build: spark
        command: src/streaming_factory.py context_streamer
        entrypoint: /bin/bash ./scripts/python-start.sh
        environment:
            BROKER_HOSTNAME: dbz-kafka:9092

    spark-cache-streamer:
        build: spark
        command: src/streaming_factory.py cache_streamer
        entrypoint: /bin/bash ./scripts/python-start.sh
        environment:
            BROKER_HOSTNAME: dbz-kafka:9092

volumes:
    checkpoint:

version: '3.8'
