networks:
    default:
        name: engage_network
        external: TRUE

services:
    mssql:
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: SuperP4ssword!
        healthcheck:
            test: |
                /opt/mssql-tools/bin/sqlcmd \
                    -S localhost -U sa -P "$$SA_PASSWORD" \
                    -Q "SELECT 1" || exit 1
        image: mcr.microsoft.com/mssql/server:2019-CU12-ubuntu-20.04
        ports:
            - 1433:1433

    mssql-startup:
        build: mssql
        depends_on:
            - mssql
        environment:
            MSSQL_HOST: mssql
            MSSQL_PORT: 1433
            MSSQL_USER: sa
            MSSQL_PASSWD: SuperP4ssword!
            CSV_PATH: /home/mssql/output/csv

    hadoop:
        build: hadoop
        healthcheck:
            test: wget --spider localhost:9870 || exit 1
            timeout: 90s
        volumes:
            - ./config:/etc/hadoop
        ports:
            - 9870:9870
            - 8020:8020

    hadoop-datanode:
        build: hadoop
        command: hdfs datanode
        depends_on:
            - hadoop
        volumes:
            - ./config:/etc/hadoop
        healthcheck:
            test: wget --spider localhost:9864 || exit 1
            timeout: 90s

    mongodb:
        build: mongo
        command: --replSet rs0 --auth
        healthcheck:
            test: |
                mongo --eval 'db.runCommand("ping").ok' \
                    localhost:27017/test --quiet
        ports:
            - 27017:27017

    mongodb-ui:
        image: mongo-express
        depends_on:
            - mongodb
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_AUTH_USERNAME: admin
            ME_CONFIG_MONGODB_AUTH_PASSWORD: admin
        healthcheck:
            test: wget --spider localhost:8081 || exit 1
        ports:
            - 8081:8081

    redis:
        image: redis:6.2.5-alpine
        healthcheck:
            test: redis-cli ping || exit 1
        ports:
            - 6379:6379

version: '3.8'
