networks:
    default:
        name: engage_network
        external: TRUE

services:
    dbz-connect:
        build: debezium/connect
        command: /create-connector.sh
        depends_on:
            - dbz-kafka
            - dbz-zookeeper
        environment:
            GROUP_ID: 1
            BOOTSTRAP_SERVERS: dbz-kafka:9092
            CONFIG_STORAGE_TOPIC: storage.config
            OFFSET_STORAGE_TOPIC: storage.offset
            STATUS_STORAGE_TOPIC: storage.status
        ports:
            - 8083:8083

    dbz-kafka:
        build: debezium/kafka
        depends_on:
            - dbz-zookeeper
        environment:
            ZOOKEEPER_CONNECT: dbz-zookeeper:2181
            CREATE_TOPICS: |
                storage.config:1:1:compact,\
                storage.offset:1:1,\
                storage.status:1:1,\
                connect.sqlserver:1:1
        ports:
            - 9092:9092
        volumes:
            - kafka-data:/var/lib/kafka/data

    dbz-zookeeper:
        image: debezium/zookeeper:1.6
        ports:
            - 2181:2181
        volumes:
            - zookeeper-data:/var/lib/zookeeper/data
            - zookeeper-logs:/var/lib/zookeeper/log

    ctrl-center:
        image: confluentinc/cp-enterprise-control-center
        environment:
            CONTROL_CENTER_BOOTSTRAP_SERVERS: dbz-kafka:9092
            CONTROL_CENTER_CONNECT_CLUSTER: http://dbz-connect:8083
            CONTROL_CENTER_REPLICATION_FACTOR: 1
            CONFLUENT_METRICS_TOPIC_REPLICATION: 1
        ports:
            - 9021:9021

volumes:
    kafka-data:
    zookeeper-data:
    zookeeper-logs:

version: '3.8'
