networks:
    default:
        name: engage_network
        external: TRUE

services:
    mssql:
        build: mssql
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: SuperP4ssword!
            CSV_PATH: /home/mssql/output/csv
        healthcheck:
            test: |
                /opt/mssql-tools/bin/sqlcmd \
                    -S localhost -U sa -P "$$SA_PASSWORD" \
                    -Q "SELECT 1" || exit 1
        ports:
            - 1433:1433

    hadoop:
        build: hadoop
        healthcheck:
            test: wget --spider localhost:9870 || exit 1
            timeout: 90s
        volumes:
            - ./config:/etc/hadoop
        ports:
            - 9870:9870
            - 8020:8020

    hadoop-datanode:
        build: hadoop
        command: hdfs datanode
        depends_on:
            - hadoop
        volumes:
            - ./config:/etc/hadoop
        healthcheck:
            test: wget --spider localhost:9864 || exit 1
            timeout: 90s

    mongodb:
        build: mongo
        command: --replSet rs0 --auth
        healthcheck:
            test: |
                mongo --eval 'db.runCommand("ping").ok' \
                    localhost:27017/test --quiet
        ports:
            - 27017:27017

    redis:
        image: redis:6.2.5-alpine
        healthcheck:
            test: redis-cli ping || exit 1
        ports:
            - 6379:6379

version: '3.8'
