networks:
    default:
        name: engage_network
        external: TRUE

services:
    dbz-connect:
        build: debezium/connect
        depends_on:
            - dbz-kafka
            - dbz-zookeeper
        environment:
            GROUP_ID: 1
            BOOTSTRAP_SERVERS: dbz-kafka:9092
            CONFIG_STORAGE_TOPIC: storage.config
            OFFSET_STORAGE_TOPIC: storage.offset
            STATUS_STORAGE_TOPIC: storage.status
        ports:
            - 8083:8083

    dbz-kafka:
        build: debezium/kafka
        depends_on:
            - dbz-zookeeper
        environment:
            ZOOKEEPER_CONNECT: dbz-zookeeper:2181
            CREATE_TOPICS: |
                storage.config:1:1:compact,\
                storage.offset:1:1,\
                storage.status:1:1,\
                connect.sqlserver:1:1
        ports:
            - 9092:9092
        volumes:
            - kafka-data:/var/lib/kafka/data

    dbz-startup:
        build: debezium/startup
        depends_on:
            - dbz-connect
        environment:
            DBZ_SOURCE: mssql:1433
            DBZ_CONNECT: dbz-connect:8083

    dbz-zookeeper:
        image: debezium/zookeeper:1.6
        ports:
            - 2181:2181
        volumes:
            - zookeeper-data:/var/lib/zookeeper/data
            - zookeeper-logs:/var/lib/zookeeper/log

    dbz-ui:
        depends_on:
            - dbz-connect
        environment:
            KAFKA_CONNECT_URI: http://dbz-connect:8083
        image: debezium/debezium-ui:1.6
        ports:
            - 8080:8080

volumes:
    kafka-data:
    zookeeper-data:
    zookeeper-logs:

version: '3.8'
