networks:
    default:
        name: engage_network
        external: TRUE

services:
    spark-raw-sink:
        build: spark
        command: src/streaming_factory.py raw_streamer
        environment:
            BROKER_HOSTNAME: dbz-kafka:9092
        ports:
            - 4040:4040
        volumes:
            - ./spark/src:/opt/spark/src
            - ./config:/etc/hadoop

    spark-aggregate_answers:
        build: spark
        command: src/aggregate_answers.py
        environment:
            BROKER_HOSTNAME: dbz-kafka:9092
        ports:
            - 4041:4041
        volumes:
            - ./spark/src:/opt/spark/src
            - ./config:/etc/hadoop

version: '3.8'
